/**
 * UNITY_PIPELINE.md §U1 — `game-unity-project` exporter.
 *
 * Bundles a Unity 6 LTS project tree into a portable ZIP with:
 *   - Every authored file under the project root
 *   - A `.gitignore` that excludes the per-machine cache (`Library/`,
 *     `Temp/`, `Logs/`, `obj/`, `*.csproj`, `*.sln`) Unity regenerates
 *     on first open
 *   - A README pointing the user at Unity Hub with the open-then-press-Play path
 *
 * Cache files are filtered at zip time even if they slipped into the
 * bundle; the model is told not to author them, but defence-in-depth.
 *
 * Phase U3 will add `game-unity-build` (the headless build output) on top.
 * This U1 exporter is the always-available baseline.
 */

import { CodesignError, ERROR_CODES } from '@open-codesign/shared';
import type { ExportResult } from './index';
import type { ZipAsset } from './zip';

export interface ExportGameUnityProjectOptions {
  files: ZipAsset[];
  designName?: string;
  /** Editor version to surface in the README. Defaults to '6000.0'. */
  engineVersion?: string;
}

const UNITY_GITIGNORE = `# Unity per-machine cache — regenerated on first open.
# Do NOT commit. The exporter excludes these on the way in.
[Ll]ibrary/
[Tt]emp/
[Oo]bj/
[Bb]uild/
[Bb]uilds/
[Ll]ogs/
[Uu]ser[Ss]ettings/

# Generated IDE solution + csproj files (regenerated by Unity).
*.csproj
*.unityproj
*.sln
*.suo
*.tmp
*.user
*.userprefs
*.pidb
*.booproj
*.svd
*.pdb
*.mdb
*.opendb
*.VC.db

# OS / editor cruft
.DS_Store
Thumbs.db
.idea/
.vscode/
`;

function readme(opts: ExportGameUnityProjectOptions): string {
  const name = opts.designName ?? 'Unity project';
  const version = opts.engineVersion ?? '6000.0';
  return `# ${name}

Exported from [open-codesign](https://github.com/OpenCoworkAI/open-codesign) — game-mode (Unity ${version}).

## How to run

1. Install [Unity Hub](https://unity.com/download). Personal license is free.
2. From Unity Hub, install Unity Editor **${version}** or newer (Unity 6 LTS).
3. Open Unity Hub → **Open** → select the unzipped project folder (the one with \`ProjectSettings/\`).
4. Unity will compile scripts and import assets on first open (~1 min on a small project).
5. Press **Play** in the top toolbar to run the scene.

## Layout

\`\`\`
.
├── Assets/
│   ├── Scenes/Main.unity      Root scene
│   ├── Scripts/                C# behaviours
│   ├── Prefabs/                Reusable game objects
│   └── Resources/              Runtime-loaded assets (Resources.Load path-relative)
├── Packages/manifest.json     Package dependencies
├── ProjectSettings/           Project + version + input settings
└── README.md                  this file
\`\`\`

## Build for desktop / WebGL / Steam

This export is the **author-time** project tree. To produce a runnable binary:

- **From the Unity Editor:** *File → Build Settings* → pick a target → *Build*.
- **From open-codesign (U3 ships in a future release):** the in-app *Build* button
  invokes the Editor in batch mode and writes a \`.app\` / \`.exe\` / \`.x86_64\` next
  to the project. The same flow can upload to Steam (U4) once Steamworks credentials
  are configured in Settings.

## Notes

- This is Unity 6 LTS (\`m_EditorVersion: ${version}\`). Trying to open in Unity 2021
  or older will fail with a compatibility error.
- The exporter excludes \`Library/\`, \`Temp/\`, \`Logs/\`, \`*.csproj\`, \`*.sln\` —
  Unity regenerates them on first open. The included \`.gitignore\` keeps your
  repo clean if you commit this project somewhere.
- Generated: ${new Date().toISOString()}
`;
}

/** Files Unity regenerates on first open — never include them in an export,
 *  even if they accidentally landed in the source bundle. */
function isUnityCacheFile(path: string): boolean {
  const lower = path.toLowerCase();
  return (
    lower.startsWith('library/') ||
    lower.startsWith('temp/') ||
    lower.startsWith('obj/') ||
    lower.startsWith('logs/') ||
    lower.startsWith('build/') ||
    lower.startsWith('builds/') ||
    lower.startsWith('usersettings/') ||
    lower.endsWith('.csproj') ||
    lower.endsWith('.sln') ||
    lower.endsWith('.suo') ||
    lower.endsWith('.user') ||
    lower.endsWith('.tmp') ||
    lower.endsWith('.pdb') ||
    lower.endsWith('.opendb')
  );
}

export async function exportGameUnityProject(
  destinationPath: string,
  opts: ExportGameUnityProjectOptions,
): Promise<ExportResult> {
  if (opts.files.length === 0) {
    throw new CodesignError(
      'game-unity-project export called with an empty file list',
      ERROR_CODES.EXPORTER_INPUT_INVALID,
    );
  }
  // Sanity: ProjectVersion.txt must exist or the user gets a non-importable
  // archive. Surface the error early instead of producing a useless zip.
  const hasProjectVersion = opts.files.some((f) => f.path === 'ProjectSettings/ProjectVersion.txt');
  if (!hasProjectVersion) {
    throw new CodesignError(
      'game-unity-project export requires ProjectSettings/ProjectVersion.txt in the file bundle.',
      ERROR_CODES.EXPORTER_INPUT_INVALID,
    );
  }

  const fs = await import('node:fs/promises');
  const path = await import('node:path');
  const os = await import('node:os');
  const { Zip } = await import('zip-lib');

  const stagingDir = await fs.mkdtemp(path.join(os.tmpdir(), 'codesign-game-unity-'));
  const stagingResolved = path.resolve(stagingDir);
  try {
    const zip = new Zip();
    const seen = new Set<string>();
    for (const file of opts.files) {
      const normalized = file.path.replace(/\\/g, '/').replace(/^\/+/, '');
      if (isUnityCacheFile(normalized)) continue;
      const localPath = path.resolve(stagingDir, normalized);
      const rel = path.relative(stagingResolved, localPath);
      if (!rel || rel.startsWith('..') || path.isAbsolute(rel)) {
        throw new CodesignError(
          `game-unity-project rejected unsafe path: ${file.path}`,
          ERROR_CODES.EXPORTER_ZIP_UNSAFE_PATH,
        );
      }
      await fs.mkdir(path.dirname(localPath), { recursive: true });
      await fs.writeFile(localPath, file.content);
      zip.addFile(localPath, normalized);
      seen.add(normalized.toLowerCase());
    }

    if (!seen.has('.gitignore')) {
      const giPath = path.join(stagingDir, '.gitignore');
      await fs.writeFile(giPath, UNITY_GITIGNORE, 'utf8');
      zip.addFile(giPath, '.gitignore');
    }

    if (!seen.has('readme.md')) {
      const readmePath = path.join(stagingDir, 'README.md');
      await fs.writeFile(readmePath, readme(opts), 'utf8');
      zip.addFile(readmePath, 'README.md');
    }

    await zip.archive(destinationPath);
    const stat = await fs.stat(destinationPath);
    return { bytes: stat.size, path: destinationPath };
  } finally {
    await fs.rm(stagingDir, { recursive: true, force: true }).catch(() => undefined);
  }
}
