import { describe, expect, it } from 'vitest';
import { createGameArtifact, listGameArtifacts } from './game-artifacts-db';
import {
  importGameArtifactFiles,
  indexGameArtifactsFromFiles,
  inferPngDimensions,
  regenerateArtifactsRegistry,
} from './game-artifacts-import';
import { createDesign, initInMemoryDb, listDesignFiles, upsertDesignFile } from './snapshots-db';

describe('inferPngDimensions', () => {
  it('reads width/height from a 1x1 PNG signature', () => {
    // Minimal valid 1x1 PNG generated by `pngcrush` style
    const tinyPng = Buffer.from(
      '89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c4890000000d49444154789c63600100000005000164a0a96b0000000049454e44ae426082',
      'hex',
    );
    expect(inferPngDimensions(tinyPng)).toEqual({ width: 1, height: 1 });
  });

  it('returns null on a non-PNG buffer', () => {
    expect(inferPngDimensions(Buffer.from('hello'))).toBeNull();
  });
});

describe('importGameArtifactFiles', () => {
  it('creates a sprite under assets/sprites/<slug>/ and links file refs', () => {
    const db = initInMemoryDb();
    const design = createDesign(db, 'fixture');
    const result = importGameArtifactFiles({
      db,
      designId: design.id,
      kind: 'sprite',
      name: 'Hero Knight',
      files: [
        {
          relativePath: 'hero.png',
          content:
            'data:base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkAAIAAAoAAv/lxKUAAAAASUVORK5CYII=',
        },
      ],
    });
    expect(result.primaryPath).toBe('assets/sprites/hero-knight/hero.png');
    const files = listDesignFiles(db, design.id);
    expect(files.find((f) => f.path === 'assets/sprites/hero-knight/hero.png')).toBeDefined();
    const artifacts = listGameArtifacts(db, design.id, { kind: 'sprite' });
    expect(artifacts).toHaveLength(1);
    expect(artifacts[0]?.slug).toBe('hero-knight');
    expect(artifacts[0]?.files).toHaveLength(1);
    expect(artifacts[0]?.files[0]?.role).toBe('texture');
  });

  it('rejects animation imports without a target sprite', () => {
    const db = initInMemoryDb();
    const design = createDesign(db, 'fixture');
    expect(() =>
      importGameArtifactFiles({
        db,
        designId: design.id,
        kind: 'animation',
        files: [{ relativePath: 'walk.json', content: '{}' }],
      }),
    ).toThrow(/targetSpriteId/);
  });
});

describe('indexGameArtifactsFromFiles', () => {
  it('promotes assets/sprites/* and assets/animations/* directories into artifact rows', () => {
    const db = initInMemoryDb();
    const design = createDesign(db, 'fixture');
    upsertDesignFile(
      db,
      design.id,
      'assets/sprites/hero/sprite.png',
      'data:base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkAAIAAAoAAv/lxKUAAAAASUVORK5CYII=',
    );
    upsertDesignFile(db, design.id, 'assets/sprites/hero/atlas.json', '{}');
    upsertDesignFile(db, design.id, 'assets/animations/walk/clip.json', '{"fps": 12}');

    const result = indexGameArtifactsFromFiles(db, design.id);
    expect(result.spritesAdded).toBe(1);
    expect(result.animationsAdded).toBe(1);

    const sprites = listGameArtifacts(db, design.id, { kind: 'sprite' });
    expect(sprites[0]?.slug).toBe('hero');
    expect(sprites[0]?.provenance.source).toBe('indexed-from-files');

    // Re-running is idempotent — no duplicate artifact rows are created.
    const second = indexGameArtifactsFromFiles(db, design.id);
    expect(second.spritesAdded).toBe(0);
    expect(second.animationsAdded).toBe(0);
  });
});

describe('regenerateArtifactsRegistry', () => {
  it('writes a deterministic JSON manifest mirroring the registry', () => {
    const db = initInMemoryDb();
    const design = createDesign(db, 'fixture');
    createGameArtifact(db, {
      designId: design.id,
      kind: 'sprite',
      name: 'Hero',
      metadata: { version: 1, kind: 'sprite', visualType: '2d-sprite', tags: [], frameCount: 1 },
      fileRefs: [],
    });
    regenerateArtifactsRegistry(db, design.id);
    const file = listDesignFiles(db, design.id).find(
      (f) => f.path === 'assets/artifacts.registry.json',
    );
    expect(file).toBeDefined();
    const parsed = JSON.parse(file?.content ?? '{}');
    expect(parsed.schemaVersion).toBe(1);
    expect(parsed.sprites[0].alias).toBe('@sprite:hero');
  });
});
